# Configure generation of web page(s) on https://lamp-guide.metamath.org
# https://stackoverflow.com/questions/46375765/how-do-you-remove-header-on-github-pages
name: Metamath-lamp Guide
# Don't insert the name of the repo at the beginning:
title: null
kramdown:
  # See: https://dieghernan.github.io/chulapa-101/cheatsheets/02-kramdown-cheat-sheet
  toc_levels: 2..6
#
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      description: This is a guide for metamath-lamp, including both a user guide (tutorial) and a reference guide. Metamath-lamp (Lite Assistant for Metamath Proofs) is a proof assistant for creating formal mathematical proofs in the Metamath system.
